
import { GoogleGenAI } from "@google/genai";
import { CLAPINGO_BRAND_GUIDELINES } from "../constants";

export const generateBlogImage = async (prompt: string): Promise<string> => {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY || "" });
  
  const fullPrompt = `
    TASK: Generate a professional editorial blog illustration for Clapingo (an English learning brand).
    PROMPT TOPIC: "${prompt}"
    
    ${CLAPINGO_BRAND_GUIDELINES}
    
    The image must be a 1200x628 landscape illustration. 
    It must feature a bold headline like: "${prompt.toUpperCase()}".
    Ensure the Clapingo logo is in the top right corner.
  `;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [{ text: fullPrompt }],
      },
      config: {
        imageConfig: {
          aspectRatio: "16:9",
        },
      },
    });

    if (!response.candidates?.[0]?.content?.parts) {
      throw new Error("No image generated by the model.");
    }

    const imagePart = response.candidates[0].content.parts.find(p => p.inlineData);
    
    if (imagePart?.inlineData?.data) {
      return `data:image/png;base64,${imagePart.inlineData.data}`;
    }

    throw new Error("No image data found in response.");
  } catch (error) {
    console.error("Image generation failed:", error);
    throw error;
  }
};
